[project]
name = "langgraph_learning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "clear>=2.0.0",
    "graphviz>=0.21",
    "langgraph>=1.0.3",
    "notebook>=7.4.7",
    "python-dotenv>=1.2.1",
]
